### PR TITLE
Add iterator() to SearchResult to loop over all the found issues

### PR DESCRIPTION
**Pull request by psiegman**
Hi Bob,

I've hadded an iterator() method to the SearchResult that pages over all search results in a way that is transparant for the users.
This saves the user the effort of implementing paging themselves.

The implementation has some quirks to keep backwards compatibility with the current SearchResult api.

regards,
                                       Paul

### CODE REVIEW

**Comment by nach-o-man** [comment]
Related to #80

**Comment by rcarz** [comment]
Thanks you!

**Comment by mkobylarz** [comment]
This patch is not too good and I suggest to revert it. 
- it breaks contract and it is not backward compatible, because now JiraClient.searchIssues throws RuntimeException instead of JiraException 
- it breaks JiraClient.searchIssues: notice that paging parameter 'startAt' to SearchResult constructor is never used, Issue.java:674):
```
	    public SearchResult(RestClient restclient, String jql,
	            String includedFields, String expandFields, Integer maxResults, Integer startAt) throws JiraException {
			this.restclient = restclient;
			this.jql = jql;
			this.includedFields = includedFields;
			this.expandFields = expandFields;
			initSearchResult(maxResults, start);
        }
```
- it is quite messy and unreliable, fixing 'startAt' moved the problem forward and there is an issue in IssueIterator.getNextIssues (Issue.java:626)
I think method should start like this (I am not sure, but it worked for me):
```
private List<Issue> getNextIssues() throws JiraException {
			if (issues != null) {
				startAt = startAt + issues.size();
			}

	        JSON result = null;
....
....
```

**Comment by mkobylarz** [comment]
Next day of tracking bugs caused by this patch, Issue.java:597:

```
currentPage = getNextIssues().iterator();
if (currentPage == null) {
	return null;
} else {
	return currentPage.next();
}
```

iterator() never returns null although it may return empty iterator, I supposed author meant:
`if (!currentPage.hasNext())`

**Comment by rcarz** [comment]
@mkobylarz The null issue should be fixed in #159. The other two issues still need to be addressed.

**Pull request merged**
