### PR TITLE
Removed unused dependencies. Fixed scope

### PR DESCRIPTION
**Pull request by iNikem**
Solves issue-57

### CODE REVIEW

**Comment by iNikem** [comment]
Solves issue-57

**Comment by iNikem** [comment]
@rcarz Any objections against merging this PR?

**Comment by rcarz** [comment]
No objects... thanks!

**Comment by iNikem** [comment]
@rcarz Have you merged this PR? It seems to me you have just closed it.

**Comment by rcarz** [comment]
It was late... I clicked the big green button without reading carefully.

**Pull request merged**
