### PR TITLE
Add support for 'any' type conversion to JSON

### PR DESCRIPTION
**Pull request by cholin-bmc**
This is an attempt to provide a fix for issue: #197

### CODE REVIEW

**Comment by cholin-bmc** [comment]
With the proposed changes, I was able to set the 'Epic' of an issue using the custom field as described in the issue description.

**Comment by ajbrown** [comment]
@rcarz Any word on when you might be able to get this cut into a release?  I currently have a project that needs this.

**Comment by rcarz** [comment]
Thanks and sorry for the long wait.

**Comment by eitzenbe** [comment]
and me too waiting on this!

**Pull request merged**
