### PR TITLE
fluent remote link issue creation

### PR DESCRIPTION
**Pull request by pejobo**
I made a fluent api for remote links, based on the description of the rest api at https://developer.atlassian.com/jiradev/jira-platform/other/guide-jira-remote-issue-links/fields-in-remote-issue-links

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
it would be nice to include some tests as well...

**Comment by pejobo** [comment]
added new tests, one for the new fluent api and one for the old "addRemoteLink", which is now a short cut and calls the new fluent api

**Comment by alexeyOnGitHub** [comment]
great, thank you!

**Comment by pejobo** [comment]
Anything blocking this? If so please let me know.

**Comment by rcarz** [comment]
No, it looks good. Thanks for the PR!

**Pull request merged**
